In [16]:
import numpy as np
data1=[1,2,3,4]

In [18]:
arr1=np.array(data1)


In [19]:
arr1

array([1, 2, 3, 4])

In [23]:
import numpy as np
data2=[[1,2,3,4],[4,3,2,1]]

In [24]:
arr2=np.array(data2)

In [25]:
arr2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 4)

In [35]:
import numpy as np
arr=np.empty((8,4))


In [ ]:
for i in range(4):
    arr[i]=i

In [33]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])